apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  DB_NAME: analyticsdb
  DB_USER: vagiadmindb
  DB_HOST: postgresql-service
  DB_PORT: 5433
---
apiVersion: v1
kind: Secret
metadata:
  name: DB_PASSWORD_ENCRYPTED
type: Opaque
data:
  DB_PASSWORD: dGVzdEAxMjM=