apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-postgresql
data:
  DB_NAME: "analyticsdb"
  DB_USER: "vagiadmindb"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpassword-encrypted
type: Opaque
data:
  DB_PASSWORD: dGVzdDEyMw==